
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update

name: isen

mybatis:
  config-location: classpath:/config/mybatis/mybatis-config.xml
#  mapper-locations:
logging:
  level:
    com.example.isen.mapper.UserMapper: debug
